<?php
require_once __DIR__ . '/vendor/autoload.php';

define('STRIPE_SECRET_KEY_PATH', '/home/ubuntu/stripe_secret.txt');
define('STRIPE_PUB_KEY_PATH', '/home/ubuntu/stripe_public.txt');

/**
 * Echos a javascript button which builds the Stripe checkout
 * $email: The customer's provided email
 * $amount: the amount in cents to show on the button
 */
function getStripeCheckout($email, $amount) {
    $stripe_pub_key = trim(file_get_contents(STRIPE_PUB_KEY_PATH));
    echo <<<END

    <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="$stripe_pub_key"
        data-amount="$amount"
        data-email="$email"
        data-name="Decatur Makerspace"
        data-description="Membership"
        data-label="Pay with Card (secured by Stripe)"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-locale="auto"
        data-currency="usd"
        data-zip-code="true"
        data-allow-remember-me="false">
    </script>

END;
}

/**
 * Echos a javascript button which builds the Stripe update card button
 * $email: The customer's stored email
 */
function getStripeUpdateCard($email) {
    $stripe_pub_key = trim(file_get_contents(STRIPE_PUB_KEY_PATH));
    echo <<<END
    <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="$stripe_pub_key"
        data-email="$email"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-name="Decatur Makerspace"
        data-panel-label="Update Card Details"
        data-label="Update Card Details"
        data-allow-remember-me=false
        data-locale="auto">
    </script>
END;
}

/**
 * Returns a Stripe customer object created from the token generated by checkout
 */
function createStripeCustomer($email, $token) {
    $stripe_secret_key = trim(file_get_contents(STRIPE_SECRET_KEY_PATH));
    \Stripe\Stripe::setApiKey($stripe_secret_key);

    $customer = \Stripe\Customer::create(array(
      "email" => $email,
      "source" => $token,
    ));

    return $customer;
}

/**
 * Returns a Stripe customer object that already exists in our user base
 */
function retrieveStripeCustomer($customer_id) {
    $stripe_secret_key = trim(file_get_contents(STRIPE_SECRET_KEY_PATH));
    \Stripe\Stripe::setApiKey($stripe_secret_key);

    $customer = \Stripe\Customer::retrieve($customer_id);
    return $customer;
}

/**
 * Updates the stored card for a Stripe customer
 * $customer_id: The ID of the customer to update
 * $token: The token returned by Stripe checkout
 */
function updateStripeCustomerCard($customer_id, $token) {
    $stripe_secret_key = trim(file_get_contents(STRIPE_SECRET_KEY_PATH));
    \Stripe\Stripe::setApiKey($stripe_secret_key);

    $result;
    try {
        $cu = \Stripe\Customer::retrieve($customer_id);
        $cu->source = $token;
        $cu->save();
        $result = "Your card details have been updated!";
    } catch(\Stripe\Error\Card $e) {
        $body = $e->getJsonBody();
        $err  = $body['error'];
        $result = $err['message'];
    }
    return $result;
}

/**
 * Returs a Stripe plan
 */
function retrieveStripePlan($id) {
    $stripe_secret_key = trim(file_get_contents(STRIPE_SECRET_KEY_PATH));
    \Stripe\Stripe::setApiKey($stripe_secret_key);

    $plan = \Stripe\Plan::retrieve($id);
    return $plan;
}

/**
 * Charge a stripe customer an amount (one time)
 */
function chargeStripeCustomer($id, $amount) {
    $stripe_secret_key = trim(file_get_contents(STRIPE_SECRET_KEY_PATH));
    \Stripe\Stripe::setApiKey($stripe_secret_key);

    $charge = \Stripe\Charge::create(array(
      "amount" => $amount,
      "currency" => "usd",
      "customer" => $id
    ));

    return $charge;
}

/**
 * Subscribe a stripe customer to a plan (recurring)
 */
function subscribeStripeCustomer($id, $plan) {
    $stripe_secret_key = trim(file_get_contents(STRIPE_SECRET_KEY_PATH));
    \Stripe\Stripe::setApiKey($stripe_secret_key);

    \Stripe\Subscription::create(array(
      "customer" => $id,
      "plan" => $plan,
    ));
}

/**
 * Updates the secret key for Stripe
 */
function updateStripeSecret($newSecret) {
    file_put_contents(STRIPE_SECRET_KEY_PATH, $newSecret);
}

/**
 * Gets the secret key for Stripe
 */
function getStripeSecret() {
    return file_get_contents(STRIPE_SECRET_KEY_PATH);
}

/**
 * Updates the public key for Stripe
 */
function updateStripePublic($newPublic) {
    file_put_contents(STRIPE_PUB_KEY_PATH, $newPublic);
}

/**
 * Gets the public key for Stripe
 */
function getStripePublic() {
    return file_get_contents(STRIPE_PUB_KEY_PATH);
}